---
detectors:
  NilCheck:
    enabled: false
  RepeatedConditional:
    enabled: false
directories:
  "test":
    IrresponsibleModule:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
