version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    ports:
      - "9092:9092"
      - "9093:9093"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: debezium
      POSTGRES_PASSWORD: debezium
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      [
        "postgres",
        "-c",
        "wal_level=logical",
        "-c",
        "max_replication_slots=10",
        "-c",
        "max_wal_senders=10",
      ]

  debezium:
    image: quay.io/debezium/connect:latest
    restart: always
    depends_on:
      - kafka
      - postgres
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      CONFIG_STORAGE_TOPIC: debezium_configs
      OFFSET_STORAGE_TOPIC: debezium_offsets
      STATUS_STORAGE_TOPIC: debezium_status
    ports:
      - "8083:8083"

  # reader:
  #   image: ruby:3.3
  #   volumes:
  #     - .:/usr/src/app
  #   working_dir: /usr/src/app
  #   command: bash -c "bundle && bundle exec ruby reader.rb"
  #   depends_on:
  #     - kafka

  # writer:
  #   image: ruby:3.3
  #   volumes:
  #     - .:/usr/src/app
  #   working_dir: /usr/src/app
  #   command: bash -c "bundle && bundle exec ruby writer.rb"
  #   depends_on:
  #     - kafka

volumes:
  postgres_data:
