name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - run: |
          bundle exec rubocop --format github
  reek:
    name: Reek
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - run: |
          bundle exec reek ./lib --format github
  bundler_audit:
    name: Bundler Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - run: |
          bundle exec bundler-audit check --update
  licensed:
    name: Licensed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - run: |
          bundle exec licensed cache
          bundle exec licensed status
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
      - run: |
          npx prettier --check '**/*.{yml,md}'
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.2", "3.3", "3.4"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - name: Test
        run: |
          bundle exec rake test
      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.ruby }}
