name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
      - name: RuboCop
        run: |
          bundle exec rubocop --format github
      - name: Prettier
        run: |
          npx prettier --check '**/*.{yml,md}'
      - name: Bundler Audit
        run: |
          bundle exec bundler-audit check --update
      - name: Licensed
        run: |
          licensed cache
          licensed status
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.2", "3.3", "3.4"]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Test
        run: |
          bundle exec rake test
      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.ruby }}
